"""add ai analysis fields

Revision ID: 36b81bad88a7
Revises: 48f216e82069
Create Date: 2026-07-25 00:13:51.011108

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '36b81bad88a7'
down_revision: str | Sequence[str] | None = '48f216e82069'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('priority', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('analysis_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'analysis_json')
    op.drop_column('leads', 'budget')
    op.drop_column('leads', 'priority')
    op.drop_column('leads', 'summary')
    # ### end Alembic commands ###
